import { z } from "zod";

export const INVITATION_REVISION = "memory-invitations-v1" as const;
export const ResearchReference = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  url: z.url(),
  evidenceType: z.enum(["empirical", "professional_guidance"]),
  readScope: z.enum(["full_text", "sections", "abstract"]),
  finding: z.string().min(1),
  limitation: z.string().min(1),
});
export const MEMORY_RESEARCH = z.array(ResearchReference).parse([
  {
    id: "storycorps-conversation",
    title: "StoryCorps: Tips for a Great Conversation",
    url: "https://storycorps.org/participate/tips-for-a-great-conversation/",
    evidenceType: "professional_guidance",
    readScope: "sections",
    finding:
      "Prepare open questions, follow the storyteller, and invite concrete detail while allowing the conversation to depart from the question list.",
    limitation:
      "Professional conversation guidance, not a controlled evaluation of automated prompts, memory accuracy or child engagement.",
  },
  {
    id: "smithsonian-interview",
    title: "Smithsonian Folklife and Oral History Interviewing Guide",
    url: "https://folklife.si.edu/the-smithsonian-folklife-and-oral-history-interviewing-guide/the-interview/smithsonian",
    evidenceType: "professional_guidance",
    readScope: "sections",
    finding:
      "Start comfortably, ask concise open questions, follow the narrator and optionally use meaningful objects or photographs.",
    limitation:
      "Practitioner guidance, not a trial of this app or its authored prompts.",
  },
  {
    id: "oha-best-practices",
    title: "Oral History Association: Best Practices",
    url: "https://oralhistory.org/best-practices/",
    evidenceType: "professional_guidance",
    readScope: "full_text",
    finding:
      "Agree on purpose and duration, listen, and respect refusal and access preferences.",
    limitation:
      "Professional guidance does not establish an optimal automated interview length.",
  },
  {
    id: "ford-2014",
    title:
      "Effects of task instruction on autobiographical memory specificity in young and older adults",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3916949/",
    evidenceType: "empirical",
    readScope: "sections",
    finding:
      "Specificity instructions changed younger adults' responses more than older adults' responses in a music-cued task.",
    limitation:
      "Laboratory music-cued results do not validate a particular voice interface or justify judging an individual's memory.",
  },
  {
    id: "mair-2021",
    title: "Age effects in autobiographical memory depend on the measure",
    url: "https://doi.org/10.1371/journal.pone.0259279",
    evidenceType: "empirical",
    readScope: "sections",
    finding:
      "Different memory tasks produced different age effects; specificity and detail are not interchangeable measures.",
    limitation:
      "A sparse answer is not evidence of impaired memory or an uninteresting life.",
  },
  {
    id: "herz-schooler-2002",
    title:
      "A naturalistic study of autobiographical memories evoked by olfactory and visual cues",
    url: "https://pubmed.ncbi.nlm.nih.gov/11868193/",
    evidenceType: "empirical",
    readScope: "abstract",
    finding:
      "Actual odor cues elicited more emotional recollection than corresponding visual and verbal cues.",
    limitation:
      "Asking about a smell is not the same intervention. Vividness does not prove accuracy.",
  },
  {
    id: "fivush-2011",
    title:
      "Personal and intergenerational narratives in relation to adolescents' well-being",
    url: "https://onlinelibrary.wiley.com/doi/10.1002/cd.288",
    evidenceType: "empirical",
    readScope: "sections",
    finding:
      "Intergenerational connections and perspective-taking were associated with aspects of adolescent well-being.",
    limitation:
      "Associations do not establish causation or outcomes for children aged four to seven using generated books.",
  },
  {
    id: "garry-1996",
    title:
      "Imagination inflation: Imagining a childhood event inflates confidence that it occurred",
    url: "https://staff.washington.edu/eloftus/Articles/Imagine.htm",
    evidenceType: "empirical",
    readScope: "full_text",
    finding:
      "Imagining childhood events increased later confidence that those events occurred.",
    limitation:
      "A small undergraduate study measured confidence, not proof of a fully formed false memory. Keep invention separate from source collection.",
  },
  {
    id: "oha-ethics",
    title: "Oral History Association: Statement on Ethics",
    url: "https://oralhistory.org/oha-statement-on-ethics/",
    evidenceType: "professional_guidance",
    readScope: "full_text",
    finding:
      "Narrators retain choice about subjects, participation and access to their accounts.",
    limitation:
      "Recording, family sharing and public release are different decisions; this is not therapy guidance.",
  },
]);

export const FollowUpCondition = z.enum([
  "explicit_relationship_ambiguity",
  "ritual_without_event",
  "missing_detail",
  "missing_meaning",
]);
export const MemoryInvitation = z.object({
  version: z.literal(1),
  revision: z.literal(INVITATION_REVISION),
  id: z.string().min(1),
  chapterId: z.string().min(1),
  title: z.string().min(1),
  opening: z.string().min(1),
  followUps: z
    .array(
      z.object({
        id: z.string().min(1),
        text: z.string().min(1),
        when: FollowUpCondition,
      }),
    )
    .min(1),
  alternativeEntries: z.array(z.string().min(1)).min(2),
  sensitiveGuidance: z.object({
    optional: z.literal(true),
    allowSkip: z.literal(true),
    message: z.string(),
    avoid: z.array(z.string()),
  }),
  research: z.array(ResearchReference).min(1),
  evidenceLabel: z.literal(
    "Research-informed design; these prompts have not been empirically validated.",
  ),
  creativeOpportunities: z.array(z.string().min(1)).min(1),
  creativeBoundary: z.literal(
    "For later story adaptation only; never present these ideas as remembered facts.",
  ),
});
export type MemoryInvitationRecord = z.infer<typeof MemoryInvitation>;

type Seed = [
  id: string,
  chapterId: string,
  title: string,
  opening: string,
  detail: string,
  meaning: string,
  alternativeA: string,
  alternativeB: string,
  creative: string,
];
const seeds: Seed[] = [
  [
    "before-childhood-games",
    "before",
    "Childhood games",
    "Tell me about a game you played or made up.",
    "What did you use, and what happened when you played?",
    "What made you want to play it again, if you did?",
    "The rules do not need to be complete.",
    "A solitary game or imaginary game is welcome.",
    "Let the remembered rules create playful stakes and a visual payoff.",
  ],
  [
    "before-mischief",
    "before",
    "A little mischief",
    "Tell me about some mischief from when you were younger, if there is a story you enjoy telling.",
    "What did you do, and what happened next?",
    "What stays with you about that moment?",
    "A harmless bit of rule-bending is enough.",
    "You can leave names out or choose a different memory.",
    "Build playful tension from the remembered plan and its consequences, without adding blame or danger.",
  ],
  [
    "before-secret-places",
    "before",
    "Secret places",
    "Tell me about a spot where you liked to spend time, if one comes to mind.",
    "What did you do there?",
    "What drew you back to that spot?",
    "It need not have been secret or quiet.",
    "A seat, step or patch of ground is enough.",
    "Use an intimate composition and a recurring object to make a small place feel expansive.",
  ],
  [
    "before-small-ambitions",
    "before",
    "Small ambitions",
    "What was something you hoped to do or become when you were younger?",
    "Do you remember doing anything toward that hope?",
    "What was appealing about it to you then?",
    "It might have been a wish for the afternoon rather than a plan for your life.",
    "The wish does not have to have come true.",
    "Let a child-sized desire organize the action without turning an unfulfilled wish into remembered success.",
  ],
  [
    "people-how-we-met",
    "people",
    "The day we met",
    "Tell me how you came to know someone who became part of your life.",
    "What do you remember about an early moment together?",
    "What about that beginning feels important to keep?",
    "Any kind of relationship is welcome.",
    "It is fine if the story begins before your own memory of it.",
    "Build a surprising encounter around a remembered action, object or place.",
  ],
  [
    "people-unexpected-friendship",
    "people",
    "An unexpected friendship",
    "Tell me about someone you came to know in a way that surprised you.",
    "What do you remember about one of your first encounters?",
    "What, if anything, changed as you got to know each other?",
    "A neighbor or brief acquaintance is welcome.",
    "You can begin later in the friendship if the beginning is unclear.",
    "Build a comic or surprising meeting around a source-supported particular.",
  ],
  [
    "people-someone-who-helped",
    "people",
    "Someone who helped",
    "Tell me about a small thing someone did for you that you still remember.",
    "What did that person actually do or say, if you remember?",
    "What about that gesture has stayed with you?",
    "You could start with an ordinary day.",
    "A person outside your family counts too.",
    "Let a modest act of help become a visible, consequential action for an animal character.",
  ],
  [
    "people-becoming-a-parent",
    "people",
    "Becoming a parent",
    "If becoming a parent or caring for a child is part of your story, what is a moment from the beginning you would like to keep?",
    "What do you remember doing in that moment?",
    "What about that beginning would you like the child to know?",
    "Any way of becoming a family belongs here.",
    "You may choose a later moment, or another kind of caring relationship.",
    "Make a small act of care tangible through action and scale without assuming how parenthood felt.",
  ],
  [
    "places-favorite-room",
    "places",
    "A favorite room",
    "Tell me about a room you liked spending time in. Where would you begin showing it to someone?",
    "What could you notice from that spot, if anything comes to mind?",
    "What made that place matter to you?",
    "It can be a room in any place you knew, not only your own home.",
    "Begin with one corner rather than the whole place.",
    "Let the remembered layout become an inviting animal-scale world.",
  ],
  [
    "places-journey-to-school",
    "places",
    "The journey to school",
    "What do you remember about getting to school, if that was part of your life?",
    "Is there one turn, stopping place or object along the way you remember?",
    "What did that journey mean in your day?",
    "Walking, riding and learning close to home all count.",
    "You can start with the destination if the route is hazy.",
    "Turn source-supported landmarks into a rhythmic sequence of discoveries.",
  ],
  [
    "places-moving",
    "places",
    "Moving",
    "Tell me about a time you moved from one place to another, if you would like to.",
    "Is there an object or small moment from the move you remember?",
    "What about that move feels important to keep?",
    "You do not need to explain why you moved.",
    "It can have been across the street or much farther away.",
    "Let a protected object connect old and new settings without assuming the move was welcome.",
  ],
  [
    "places-arriving-somewhere-new",
    "places",
    "Arriving somewhere new",
    "Tell me about arriving somewhere that was new to you.",
    "What is one thing you remember noticing or doing when you arrived?",
    "What stands out when you look back on that arrival?",
    "A short visit or familiar kind of place still counts.",
    "You may leave out the reason for the journey.",
    "Use changing scale and composition to convey unfamiliarity without inventing fear.",
  ],
  [
    "table-recipes",
    "table",
    "Something from our kitchen",
    "Tell me about something you or someone you knew made to eat.",
    "What is one action, ingredient or kitchen detail you remember?",
    "What makes this food part of your story?",
    "You do not need a written recipe or exact measurements.",
    "A simple snack belongs here too.",
    "Let remembered ingredients and kitchen gestures create texture, rhythm and a family-specific visual payoff.",
  ],
  [
    "table-celebrations",
    "table",
    "Celebrations",
    "Tell me about a day your family or community marked in a particular way.",
    "What would someone do to prepare or take part?",
    "What part of that day would you want to pass on?",
    "It need not be a holiday recognized by other people.",
    "You can describe your experience without speaking for everyone.",
    "Build a visual rhythm from source-supported preparations and participation.",
  ],
  [
    "table-ordinary-meals",
    "table",
    "A wonderfully ordinary meal",
    "Tell me about a meal or a way of eating that was part of your life.",
    "Is there a dish, sound, object or action you remember from it?",
    "What, if anything, made that meal or routine yours?",
    "An ordinary snack counts as much as a celebration.",
    "You can describe eating alone or with others.",
    "Build visual abundance or a playful repeated action from a remembered food ritual.",
  ],
  [
    "table-things-everyone-said",
    "table",
    "Things everyone said",
    "Was there something people often said around a meal or gathering? Tell me what you remember.",
    "When would those words come up?",
    "What do those words bring back for you?",
    "You can say the words in their original language.",
    "It is fine to remember the sense of it rather than the exact words.",
    "Use a clearly attributed family phrase as a refrain, without presenting a paraphrase as an exact quotation.",
  ],
  [
    "outdoors-adventures",
    "outdoors",
    "An adventure outdoors",
    "Tell me about an outdoor adventure, however small, that you remember.",
    "What do you remember doing during it?",
    "What made it feel like an adventure to you?",
    "A garden, a street or a patch of ground close to home is enough.",
    "Curiosity counts; danger is not required.",
    "Use the child's scale of experience to make a modest action feel wonderfully large.",
  ],
  [
    "outdoors-getting-lost",
    "outdoors",
    "Getting lost",
    "Tell me about a time you lost your way or took an unexpected turn, if it is a memory you want to share.",
    "What did you do next?",
    "What about that journey has stayed with you?",
    "It could have been a brief wrong turn.",
    "You can choose a different journey if this feels uncomfortable.",
    "Build anticipation around remembered choices and landmarks without inventing danger or a rescue.",
  ],
  [
    "outdoors-discoveries",
    "outdoors",
    "A surprising discovery",
    "Tell me about something you came across that surprised you.",
    "What first caught your attention?",
    "What made the discovery worth remembering?",
    "It can be an ordinary thing you had not noticed before.",
    "You can begin with where you were rather than naming the discovery.",
    "Let a source-supported detail become a visual reveal, preserving what was actually found.",
  ],
  [
    "outdoors-journeys",
    "outdoors",
    "A journey",
    "Tell me about a journey you remember taking.",
    "Is there one stop, sight or action along the way you can describe?",
    "What makes this journey yours to remember?",
    "A short trip counts as much as a long one.",
    "You do not need to remember dates or every stop.",
    "Use selected remembered landmarks to give the journey a satisfying visual and narrative rhythm.",
  ],
  [
    "trying-making-something",
    "trying",
    "Making something",
    "Tell me about something you made or tried to make.",
    "What do you remember doing with the materials or tools?",
    "What about making it has stayed with you?",
    "It can be ordinary, unfinished or no longer with you.",
    "Something you made with another person counts too.",
    "Give the meaningful object's exact source-supported features a role in action and payoff.",
  ],
  [
    "trying-first-job",
    "trying",
    "A first job",
    "Tell me about an early job or responsibility you remember.",
    "What would your hands or body be doing during it?",
    "What would you want someone to understand about that work?",
    "Paid work, unpaid work and caring for others all count.",
    "It need not be your very first job; choose an early task you remember.",
    "Use physical action, posture and a small practical problem to make work legible to a child.",
  ],
  [
    "trying-a-mistake",
    "trying",
    "A mistake",
    "Tell me about a time something went differently from what you intended, if there is one you feel like sharing.",
    "What happened next?",
    "How do you see that moment now?",
    "A tiny mishap is enough.",
    "You do not have to make it funny or give it a happy ending.",
    "Heighten a harmless source-supported mishap through comic escalation without altering its protected outcome.",
  ],
  [
    "trying-learning-a-skill",
    "trying",
    "Learning a skill",
    "Tell me about something you learned to do, or tried to learn.",
    "What do you remember about one attempt?",
    "What did learning it come to mean to you?",
    "It is fine if you never mastered it.",
    "An everyday skill counts as much as a special one.",
    "Let choices and attempts carry the story; preserve whether the original attempt succeeded.",
  ],
  [
    "particular-family-language",
    "particular",
    "Our family language",
    "Is there a phrase, saying or expression that belongs to your family or community? Tell me about it.",
    "When would someone use those words?",
    "What do those words mean to you in your own way?",
    "You can say it in the language you know it in.",
    "There does not have to be an exact translation.",
    "Use the narrator's protected phrase as a meaningful refrain, preserving language and attribution.",
  ],
  [
    "particular-traditions",
    "particular",
    "Our traditions",
    "Tell me about a custom or tradition that was part of your family or community.",
    "What do you remember someone doing as part of it?",
    "What would you want kept the same if it were passed on again?",
    "You can include something you chose not to continue.",
    "A small informal custom counts too.",
    "Let a repeated object or gesture connect generations without inventing a universal cultural rule.",
  ],
  [
    "particular-cherished-objects",
    "particular",
    "Cherished objects",
    "Is there an object you used, made or kept that has a story? Tell me about it.",
    "What did it look like or how did you use it, if you remember?",
    "What made it worth remembering or keeping?",
    "It can be ordinary, broken or no longer with you.",
    "A tool, garment or handwritten note could be an entry point, if one is yours.",
    "Give the meaningful object's exact source-supported features a role in action and payoff.",
  ],
  [
    "particular-unusual-habits",
    "particular",
    "Our unusual habits",
    "Was there a small thing you or your household did in a particular way? Tell me about it.",
    "How did it usually begin?",
    "What would feel different if that little ritual were missing?",
    "It might be practical, playful or hard to explain.",
    "A routine you invented yourself counts too.",
    "Use repetition with one gentle variation to give an ordinary ritual narrative shape.",
  ],
  [
    "lasting-quiet-kindness",
    "lasting",
    "Quiet kindness",
    "Tell me about a small act of kindness you remember seeing, giving or receiving.",
    "What happened, in whatever detail you want to share?",
    "What has stayed with you about that act?",
    "You could start with an ordinary day.",
    "A person outside your family counts too.",
    "Let a modest act of help become a visible, consequential action for an animal character.",
  ],
  [
    "lasting-change",
    "lasting",
    "Change",
    "Tell me about something you came to see differently over time.",
    "Is there a moment or small detail connected with that change?",
    "How would you describe the change in your own words?",
    "It need not be a dramatic revelation.",
    "It is fine if you still have mixed feelings.",
    "Let a recurring image acquire new meaning without forcing a neat resolution.",
  ],
  [
    "lasting-someone-we-miss",
    "lasting",
    "Someone we miss",
    "Is there a small thing about someone you miss that you would like to keep in a story?",
    "Is there a gesture, saying or ordinary moment that shows that part of them?",
    "What would you most like kept in the telling?",
    "They may be far away, absent from your life, or no longer living.",
    "You can share a small moment without explaining the whole relationship.",
    "Keep one distinctive action or phrase central so remembrance feels particular, not generic.",
  ],
  [
    "lasting-carrying-forward",
    "lasting",
    "Something worth carrying forward",
    "What small part of your life would you like someone in the future to know about?",
    "Is there an object, place or action that belongs with it?",
    "What would you like that future reader to understand?",
    "You can choose something from today.",
    "There is no need to make it important to anyone but you.",
    "Give an ordinary source detail visual wonder while preserving why it belongs to this person.",
  ],
];

export const MEMORY_INVITATIONS: MemoryInvitationRecord[] = seeds.map(
  ([
    id,
    chapterId,
    title,
    opening,
    detail,
    meaning,
    alternativeA,
    alternativeB,
    creative,
  ]) =>
    MemoryInvitation.parse({
      version: 1,
      revision: INVITATION_REVISION,
      id,
      chapterId,
      title,
      opening,
      followUps: [
        {
          id: `${id}:relationship`,
          text: "You mentioned being unsure about a relationship. Would you like to clarify it, or leave it uncertain?",
          when: "explicit_relationship_ambiguity",
        },
        {
          id: `${id}:occasion`,
          text: "Does one occasion come to mind? It is also fine to keep the memory as a usual routine.",
          when: "ritual_without_event",
        },
        { id: `${id}:detail`, text: detail, when: "missing_detail" },
        { id: `${id}:meaning`, text: meaning, when: "missing_meaning" },
      ],
      alternativeEntries: [alternativeA, alternativeB],
      sensitiveGuidance: {
        optional: true,
        allowSkip: true,
        message:
          "You may skip, pause or finish whenever you wish. You do not need to explain a difficult memory or turn it into a lesson.",
        avoid: [
          "Assumed happy childhoods or family structures",
          "Pressure to disclose, forgive or find a positive ending",
          "Treating silence, uncertainty or emotion as a diagnosis",
        ],
      },
      research: MEMORY_RESEARCH.filter((reference) =>
        [
          "smithsonian-interview",
          "storycorps-conversation",
          "oha-best-practices",
          "ford-2014",
          "mair-2021",
          "garry-1996",
          ...(chapterId === "lasting" ? ["oha-ethics"] : []),
          ...(chapterId === "particular" ? ["fivush-2011"] : []),
          ...(chapterId === "table" || chapterId === "places"
            ? ["herz-schooler-2002"]
            : []),
        ].includes(reference.id),
      ),
      evidenceLabel:
        "Research-informed design; these prompts have not been empirically validated.",
      creativeOpportunities: [creative],
      creativeBoundary:
        "For later story adaptation only; never present these ideas as remembered facts.",
    }),
);

export function getMemoryInvitation(id: string) {
  return MEMORY_INVITATIONS.find((invitation) => invitation.id === id);
}
